
#include "cpp_generator.h"
#include "variable.h"
#include <utf/utf.h>

namespace imgproc
{

////////////////////////////////////////

cpp_generator::cpp_generator( std::ostream &cpp )
	: _cpp( cpp )
{
	auto table = std::make_shared<function_table>( [&](const std::u32string &f ,const std::vector<type> &args )
	{
		return this->generate( f, args );
	} );

	_globals->set_functions( table );

	// Add default stuff
	_cpp << "// Generated by imgc\n";
	_cpp << "#include <imgproc/buffer.h>\n";
	_cpp << "using namespace imgproc;";
	_cpp << "\n";

	// Add built-in functions
	table->add( U"floor", std::make_shared<func>( U"floor", U"x" ) );
	table->add( U"ceil", std::make_shared<func>( U"ceil", U"x" ) );
	table->add( U"abs", std::make_shared<func>( U"abs", U"x" ) );
}

////////////////////////////////////////

void cpp_generator::add_functions( const std::vector<std::shared_ptr<func>> &funcs )
{
	auto table = _globals->functions();
	for ( auto f: funcs )
		table->add( f->name(), f );
}

////////////////////////////////////////

type cpp_generator::generate( const std::u32string &name, const std::vector<type> &types )
{
	auto sig = std::make_pair( name, types );
	auto check = _compiled.find( sig );
	if ( check != _compiled.end() )
	{
		if ( check->second.first == data_type::UNKNOWN )
			throw_runtime( "recursive function {0} not allowed", name );
		return check->second;
	}
	_compiled[sig] = { data_type::UNKNOWN, 0 };

	std::cout << "Generating " << name << std::endl;
	auto f = get_function( name );
	const auto &args = f->args();

	precondition( args.size() == types.size(), "expected {0} argument types, but got {1}", args.size(), types.size() );

	if ( !f->result() )
	{
		// Built-in function
		_compiled[sig] = types.front();
		return types.front();
	}

	auto sc = std::make_shared<scope>( _globals );
	for ( size_t a = 0; a < args.size(); ++a )
		sc->add( args[a], types[a] );

	auto t = f->result()->result_type( sc );

	std::ostringstream out;
	compile_context code( out );
	code.line();

	std::stringstream ar;
	for ( size_t a = 0; a < args.size(); ++a )
	{
		if ( a > 0 )
			ar << ", ";
		ar << cpp_type_const_ref( types[a] ) << args[a];
	}
	code.line( "{0} {1}( {2} )", cpp_type( t ), name, ar.str() );
	code.line( "{" );

	code.indent_more();
	std::string res = f->result()->compile( code, sc );
	code.line( "return {0};", res );

	code.indent_less();
	code.line( "}" );

	_cpp << out.str();

	_compiled[sig] = t;
	return t;
}

////////////////////////////////////////

std::shared_ptr<func> cpp_generator::get_function( const std::u32string &name )
{
	auto f = _globals->functions()->get( name );
	if ( !f )
		throw_runtime( "function \"{0}\" not found", name );
	return f;
}

////////////////////////////////////////

}

