name: CI Build
on:
  push:
    branches:
      - master

jobs:
  Ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Configure
      run: |
        rm -rf _build
        mkdir _build
        cmake --version
        echo "Configuring..."
        cd _build
        cmake ..
    - name: Compile
      run: make -C _build -j4
    - name: Build Tests
      run: make -C _build -j4 build_tests
    - name: Test
      run: make -C _build -j4 run_tests
#    - name: Setup
#      uses: ./.github/actions/setup-ubuntu-step
#    - name: Compile
#      uses: ./.github/actions/build-unix-step
#    - name: Test
#      uses: ./.github/actions/test-unix-step
#  macOS:
#    name: Build MacOS
#    runs-on: macos-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v1
#    - name: Setup
#      uses: ./.github/actions/setup-step
#    - name: Compile
#      uses: ./.github/actions/build-step
#    - name: Test
#      uses: ./.github/actions/test-step
#  Windows:
#    name: Build Windows
#    runs-on: windows-latest
#    steps:
#    - name: Checkout
#      uses: actions/checkout@v1
#    - name: Setup
#      uses: ./.github/actions/setup-step
#    - name: Compile
#      uses: ./.github/actions/build-step
#    - name: Test
#      uses: ./.github/actions/test-step
